name: Chapter_2_Build_with_no_cache
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          submodules: true
      - name: Using local workflow
        uses: akshat-kumar2109/Mastering-GitHub-Actions/Chapter 2/.github/workflows/build-with-no-cache.yml@main
